README.md
src/assets/icons/index.ts
src/layouts/main/config-navigation.tsx
src/layouts/main/header.tsx
src/sections/home/home-hero.tsx

- [docs] 📝 update readme
- [style] 💄 update hero title size in mobile
- [fix] 🚑 show my-wallet menu in mobile

merge feature/baseline-v2 into develop

---

README.md
src/locales/langs/br.json
src/locales/langs/en.json
src/locales/langs/es.json

- [docs] 📝 add docs auth & autz
- [fix] 🌐 improve some i18n texts

merge feature/small-fixs into develop

---

src/app/api/_data/data-service.ts
src/app/api/v1/auth/code/route.ts
src/app/api/v1/auth/login/route.ts
src/app/api/v1/user/[id]/route.ts
src/app/api/v1/wallet/[id]/transactions/route.ts

- [chore] 🔇 remove some console logs
- [chore] 🚚 remove typo in file name

merge feature/20240801-2 into develop

---

README.md

- [docs] 📝 improve documentation

merge feature/improve-docs into develop

---

README.md

. [docs] :memo: add subgraph repo to readme

merge feature/docs-subgraph into develop

---

src/components/hook-form/rhf-code.tsx
src/config-global.ts

- [feat] 🚸 improve user experience at input-code
- [build] 🔧 change default value in icp env-variable

merge feature/20240815-1 into develop

---

src/hooks/use-boolean.ts
src/layouts/common/searchbar/index.tsx
src/layouts/dashboard/nav-vertical.tsx
src/sections/account/view/user-account-view.tsx

merge feature/54 into develop

---

.github/workflows/build-check.yml

merge feature/72 into develop

---

src/app/api/_hooks/api-resolver.ts
src/app/api/v1/auth/code/route.ts
src/sections/auth/jwt/jwt-login-view.tsx

merge feature/login-send-message into develop

---

src/sections/nfts/nft-item-claim.tsx
src/sections/nfts/nft-item.tsx
src/sections/nfts/view/nft-mint-view.tsx
src/types/wallet.ts

merge fix/nft-image into develop

---

src/sections/nfts/nft-item.tsx

merge feature/nft-show-id into develop

---

public/assets/icons/home/ic_icp_dark.svg
public/assets/icons/home/ic_icp_light.svg
scripts/nfts-update-schema-copies.js
scripts/nfts-update-schema-image.js
src/layouts/common/login-button.tsx
src/layouts/main/header.tsx
src/locales/langs/br.json
src/locales/langs/en.json
src/locales/langs/es.json
src/sections/auth/jwt/jwt-register-view.tsx
src/sections/home/home-hero.tsx
src/sections/home/home-stack-tech.tsx

merge feature/20240927 into develop

---

.github/workflows/codeql-check.yml

merge feature/codeql into develop

---

src/layouts/common/login-button.tsx
src/layouts/main/header.tsx
src/locales/langs/br.json
src/locales/langs/en.json
src/locales/langs/es.json

merge feature/account-ctas into develop

---

next.config.js
src/config-global.ts
src/sections/nfts/nft-item.tsx

- [feat] ✨ allow new images domains
- [feat] ✨ update nft-contract address
- [feat] ✨ update nft image logic

merge feature/nfts into develop

---

next.config.js
src/sections/nfts/nft-item-claim.tsx

- [feat] ✨ update default image
- [feat] ✨ allow new images domain

merge feature/next-images into develop

---

src/locales/langs/br.json
src/locales/langs/en.json
src/locales/langs/es.json
src/sections/nfts/nft-item-claim.tsx
src/sections/nfts/nft-item.tsx
src/types/wallet.ts

merge feature/metatada-view into develop

---

src/config-global.ts
src/layouts/common/login-button.tsx
src/layouts/main/header.tsx

- {fix] :sparkles: refactor routes to use with icp

merge fix/paths-icp into develop

---

package.json
src/config-global.ts
src/layouts/common/login-button.tsx
src/layouts/main/header.tsx
src/routes/paths.ts

- [feat] 🔥 remove dead code
- [chore] 🔥 remove unused script
- [refactor] ♻️ refactor icp handle urls

merge feature/icp-deploy into develop

---

src/app/api/_data/data-service.ts
src/locales/langs/br.json
src/locales/langs/en.json
src/locales/langs/es.json
src/sections/nfts/nft-item.tsx
src/types/wallet.ts

merge feature/20241003-1 into develop

---

src/app/api/_data/data-service.ts
src/sections/nfts/nft-item.tsx
src/types/wallet.ts

merge feature/20240310-2 into develop

---

src/app/api/_data/blk-service.ts
src/config-global.ts
src/types/wallet.ts

- [feat] 🏷️ add new fields in balance type
- [feat] 🏷️ add default balances response
- [feat] 👽 update balance-api to new backend structure
- [feat] 👽 add call to backend endpoint to transfer-all 
- [feat] 👽 skip transfer-all backend error

merge feature/20241101 into develop

---

.doc/content.md
.doc/deployment/deployment-guidelines.md
README.md

- [docs] :memo: refactor general documentation

merge feature/readme into develop

---

src/config-global.ts

merge fix/externalize-push-env-build into develop

---

src/app/api/_hooks/use-wallet.ts
src/app/api/v1/auth/login/route.ts
src/app/api/v1/user/[id]/route.ts
src/app/api/v1/wallet/[id]/notifications/route.ts
src/config-global.ts
src/sections/account/account-general.tsx
src/sections/banking/banking-balances.tsx
src/sections/nfts/nft-item-share.tsx
src/sections/notifications/push-notifications.tsx
src/types/account.ts

- [feat] 👽 use walletEOA en push api 
- [feat] ✨ use walletEOA en notifications call 
- [feat] ✨ use walletEOA en notifications ui 
- [feat] ✨ add walletEOA en reference type
- [fix] 🌐 fix share nft button text
- [chore] ⚰️ remove dead code
- [chore] 🔇 remove console log
- [styles] 🎨 prettier

merge fix/20241229-1 into develop

---

src/app/api/_hooks/use-wallet.ts
src/app/api/v1/auth/login/route.ts
src/app/api/v1/user/[id]/route.ts
src/app/api/v1/wallet/[id]/notifications/route.ts
src/config-global.ts
src/sections/account/account-general.tsx
src/sections/banking/banking-balances.tsx
src/sections/nfts/nft-item-share.tsx
src/sections/notifications/push-notifications.tsx
src/types/account.ts

- [feat] 👽 use walletEOA en push api 
- [feat] ✨ use walletEOA en notifications call
- [feat] ✨ use walletEOA en notifications ui 
- [feat] ✨ add walletEOA en reference type
- [fix] 🌐 fix share nft button text 
- [chore] ⚰️ remove dead code
- [chore] 🔇 remove console log
- [styles] 🎨 prettier

merge release/v0.0.8 into develop

---

.gitignore
src/app/api/_data/blk-service.ts

- [fix] 👽 fix withdraw all funds endpoint name
- [chore] 🙈 add env files to ignore

merge fix/20241230 into develop

---

src/app/api/_data/blk-service.ts

- [feat] :alien: update withdraw all url

merge feature/withdrwa-all-url

---

src/app/api/v1/user/[id]/transfer-all/route.ts

- [fix] 🐛 replace id by channel_user_id

merge feature/withdraw-all-url into develop

---

src/app/api/_data/data-service.ts
src/app/api/v1/wallet/[id]/transactions/route.ts
src/locales/langs/br.json
src/locales/langs/en.json
src/locales/langs/es.json
src/sections/banking/banking-recent-transitions.tsx
src/sections/banking/view/overview-banking-view.tsx

- [feat] ✨ add type column to transactions 
- [feat] ✨ update get transactions service to handle new model (
- [feat] ✨ put default 'chatterpay' as contact in swaps

merge fix/20250109 into develop

---

next.config.js
src/app/api/v1/auth/login/route.ts
src/app/api/v1/wallet/[id]/notifications/route.ts
src/config-global.ts

- [revert] ⏪ revert refactor how to read variables from env
- [revert] ⏪ revert enable turbo pack for build
- [build] 🐛 fix build error with empty jwt_secret

merge fix/build into develop

---

src/app/api/_data/data-service.ts
src/locales/langs/br.json
src/locales/langs/en.json
src/locales/langs/es.json
src/sections/banking/banking-balances.tsx
src/sections/banking/banking-recent-transitions.tsx

- [feat] :children_crossing: improve contact name/phone showed in tranfers 
- [styles] :sparkles: improve CTAs in transfer

merge feature/20250121 into develop

---

src/app/api/_data/blk-service.ts
src/app/api/_hooks/api-resolver.ts
src/app/api/_utils/request-utils.ts
src/app/api/v1/auth/login/route.ts
src/config-global.ts
src/sections/nfts/nft-item.tsx

- [refactor] ♻️ rename ui_api_url to ui_base_url
- [fix] 🩹 fix default user photo extension
- [feat] ✨ add origin header to requests

merge feature/header-origin into develop

---

src/app/api/_data/blk-service.ts
src/app/api/_data/data-service.ts
src/app/api/_hooks/use-contact.ts
src/app/api/_utils/jwt-utils.ts
src/app/api/v1/auth/login/route.ts
src/app/api/v1/user/[id]/code/route.ts
src/app/api/v1/user/[id]/email/route.ts
src/app/api/v1/user/[id]/logout/route.ts
src/app/api/v1/user/[id]/route.ts
src/app/api/v1/user/[id]/transfer-all/route.ts
src/app/api/v1/wallet/[id]/balance/route.ts
src/app/api/v1/wallet/[id]/nfts/[nft_id]/route.ts
src/app/api/v1/wallet/[id]/nfts/route.ts
src/app/api/v1/wallet/[id]/notifications/route.ts
src/app/api/v1/wallet/[id]/transactions/route.ts
src/auth/context/jwt/auth-provider.tsx
src/auth/context/jwt/utils.ts
src/components/settings/context/settings-provider.tsx
src/config-global.ts
src/hooks/use-local-storage.ts
src/sections/auth/jwt/jwt-login-view.tsx
src/sections/banking/banking-balances.tsx
src/sections/banking/banking-recent-transitions.tsx
src/sections/banking/view/overview-banking-view.tsx
src/types/jwt.ts

- [feat] 🚸 avoid login when JWT token is stored and valid
- [feat] 👔 add optional parameters in settings-provider
- [fix] 🩹 fix view-transactions table when no jwt-token
- [fix] 🩹 fix balance view when no jwt-token
- [fix] 🩹 fix banking-view empty session user
- [fix] 🐛 fix read of app_env and node_env variables
- [fix] 🐛 add missing origin headers in call to backend get balances
- [fix] 🐛 add missing authorization header in use-contact
- [fix] 🐛 put correct getUserById function in user/id route
- [fix] 🐛 fix logout when invalid jwttoken
- [fix] 🚨 fix linter warnings
- [refactor] 🚚 rename storage keys name
- [refactor] ♻️ allow storage-hook keep items as json or string
- [refactor] 🧑‍💻 improve error flow in storage handler
- [refactor] ♻️ move jwt types to specific file
- [refactor] 🔊 …

merfe feature/improve-user-session into develop

---

README.md

- [docs] :memo: update web site link

merge fix/web-site-link into develop

---

src/locales/langs/br.json
src/locales/langs/en.json
src/locales/langs/es.json
src/sections/nfts/nft-item-share.tsx

- [fix] :bug: fix translation in nft share link

[fix] :bug: fix translation in nft share link

---

src/app/api/services/db/chatterpay-db-service.ts

- The transaction list now displays the amount minus the fee, only for transfers.
- #210

merge fix/210-transfer-fee into develop

---

src/app/api/services/db/chatterpay-db-service.ts
src/sections/banking/banking-recent-transitions.tsx
src/types/wallet.ts

- The management of subtracting the fee from the transaction amount is moved from the Mongo service to the user view, to account for the transaction type and whether the amount was received or sent.
- #210

merge fix/210-transfer-fee-2 into develop

---

src/sections/account/change-email.tsx

-  allow email change when old email is empty
- #211

merge fix/211-unable-change-email

---

src/sections/banking/banking-recent-transitions.tsx
src/utils/format-address.ts

- Added non-chatterpay address support for both mobile and desktop transfers history. 
- #216

Feat: Added support for non-chatterpay outgoing transfers in tx history

---

src/utils/format-number.ts

- It corrected the display of very small token amounts in the transaction list by allowing greater precision in number formatting. This ensures accurate representation of low-value transfers and improves the overall user experience when interacting with highly divisible tokens.
- #221

merge fix/221-inaccurate-display-small-amounts into develop

---

src/locales/langs/br.json
src/locales/langs/en.json
src/locales/langs/es.json

- Updated the founder bio texts in Spanish, English, and Portuguese to ensure similar length across all three entries per language. This helps maintain a consistent card height in the About Us section, improving visual balance and layout integrity.
- #227

merge feature/227-founders-texts into develop

---

src/app/api/services/db/chatterpay-db-service.ts
src/locales/langs/br.json
src/locales/langs/en.json
src/locales/langs/es.json
src/sections/banking/banking-recent-transitions.tsx

- Refactored the transactions UI to improve handling of external wallets, added fallbacks for transfers and deposits involving non-ChatterPay users, and enhanced i18n text clarity in the transfers module.
- #231

merge Fix/231-external-wallets-not-show-in-transfers into develop

---

src/config-global.ts

- Added links to ChatterPay’s Discord and Linktree in the footer
- #250

merge feature/250-cta-discord into develop

---

.github/workflows/ci-check.yml
Dockerfile
example_env
package.json
src/app/api/hooks/api-resolver.ts
src/app/api/hooks/use-wallet.ts
src/app/api/middleware/utils/jwt-utils.ts
src/app/api/middleware/validators/base-security-validator.ts
src/app/api/services/blockchain/blockchain-service.ts
src/app/api/v1/auth/login/route.ts
src/app/api/v1/auth/me/route.ts
src/app/api/v1/user/[id]/logout/route.ts
src/auth/context/jwt/auth-provider.tsx
src/auth/context/jwt/utils.ts
src/auth/guard/auth-guard.tsx
src/components/loading-screen/splash-screen.tsx
src/config-global.ts
src/layouts/common/login-button.tsx
src/layouts/main/header.tsx
src/sections/auth/jwt/jwt-login-view.tsx
src/sections/auth/jwt/jwt-register-view.tsx
src/sections/banking/view/overview-banking-view.tsx
src/sections/nfts/nft-list.tsx
src/sections/nfts/view/nfts-view.tsx
yarn.lock

- Applied security overrides to enforce safe versions of several transitive dependencies (`chalk`, `strip-ansi`, `color-convert`, `color-name`, `is-core-module`, etc.), in response to the [[malicious-code disclosure](https://jdstaerk.substack.com/p/we-just-found-malicious-code-in-the)](https://jdstaerk.substack.com/p/we-just-found-malicious-code-in-the). This ensures our project no longer pulls potentially compromised versions and helps mitigate supply-chain risk.
- Improved client-side session handling to prevent users from being unexpectedly logged out after a page refresh. The changes adjust how expiration is validated during initialization and API calls, ensuring that sessions are not prematurely invalidated on reload. At the same time, token expiration is still properly enforced when …

merge release/20250924 into main

---

.github/workflows/FUNDING.yml

merge feature/funding into develop
